//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by VCClient.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDS_ABOUTBOX                    101
#define IDD_VCCLIENT_DIALOG             102
#define IDR_VCCLIENT                    103
#define IDS_CLIENTCLASS_DESC            104
#define IDR_ClientClass                 105
#define IDR_MAINFRAME                   128
#define IDD_SAMPLE_DIALOG               130
#define IDD_LOGIN_DIALOG                133
#define IDD_CONTROL_DIALOG              136
#define IDD_POINT_CONTROL_DIALOG        136
#define IDR_MENU_COMM_CLIENT            137
#define IDD_ADV_CONTROL_DLG             139
#define IDC_BTN_REGISTER                1000
#define IDC_BTN_UNREGISTER              1001
#define IDC_GRP_REGISTER                1002
#define IDC_COMMAND                     1003
#define ID_CLOSE                        1004
#define IDC_BTN_SAMPLE                  1005
#define IDC_CMDNAME                     1006
#define IDC_EDIT1                       1007
#define IDC_EDIT_PANEL_HID              1007
#define IDC_EDIT_OP_NOTE                1007
#define IDC_EDIT_HID                    1008
#define IDC_MAC_NAME                    1009
#define IDC_CTP_PANEL_HID               1010
#define IDC_CMDNAME2                    1011
#define IDC_CMDNAME3                    1012
#define IDC_CMDNAME4                    1013
#define IDC_EDIT2                       1014
#define IDC_EDIT_HID_TYPE               1014
#define IDC_EDIT_BUFFER                 1015
#define IDC_EDIT3                       1016
#define IDC_EDIT_PANEL_TYPE             1016
#define IDC_ACK_ALARM                   1017
#define IDC_EDIT_DOOR_HID               1017
#define IDC_EDIT_TP_HID                 1018
#define IDC_EDIT4                       1019
#define IDC_EDIT_TP                     1020
#define IDC_EDIT_DOOR_POINTID           1020
#define IDC_EDIT7                       1021
#define IDC_EDIT_TZID                   1021
#define IDC_EDIT_DM_HID                 1022
#define IDC_EDIT5                       1023
#define IDC_EDIT_TP_UNIT                1024
#define IDC_LST_ALARM                   1025
#define IDC_EDIT_BUFFER_MODE            1026
#define IDC_LST_ACKALARM                1027
#define IDC_LST_EVENT                   1028
#define IDC_EDIT6                       1029
#define IDC_LST_STATUS                  1030
#define IDC_TREE1                       1031
#define IDC_EDIT_NXDOOR_HID             1032
#define IDC_BUTTON2                     1033
#define IDC_BTN_DEENERGIZE              1033
#define IDC_BTN_INIT_END                1033
#define IDC_BTN_LOCK                    1034
#define IDC_BUTTON3                     1035
#define IDC_BTN_PULSE                   1036
#define IDC_BUTTON4                     1037
#define IDC_BTN_UNLOCK                  1038
#define IDC_BUTTON5                     1039
#define IDC_BTN_UNSHUNT                 1040
#define IDC_BUTTON6                     1041
#define IDC_BTN_SHUNT                   1042
#define IDC_RADIO1                      1043
#define IDC_RADIO_NS_PANELS             1043
#define IDC_BUTTON7                     1044
#define IDC_BTN_TZ                      1045
#define IDC_RADIO2                      1046
#define IDC_RADIO_P_SERIES              1046
#define IDC_BUTTON8                     1047
#define IDC_BTN_BUFFER                  1048
#define IDC_BUTTON9                     1049
#define IDC_BTN_UNBUFFER                1050
#define IDC_BUTTON10                    1051
#define IDC_BTN_TIMEDPULSE              1052
#define IDC_BtnAck                      1053
#define IDC_BTNDETAILS                  1054
#define IDC_BtnClear                    1055
#define IDC_COMBO5                      1056
#define IDC_COMBO_DOORMODE              1057
#define IDC_TXT_ALRM_HID                1058
#define IDC_COMBO_DOORMODE2             1058
#define IDC_TXT_ALRM_POINTID            1059
#define IDC_LIST_ALARM                  1060
#define IDC_BTN_STATUS                  1061
#define IDC_BUTTON11                    1062
#define IDC_BTN_DOORMODE                1063
#define IDC_LST_DETAILS                 1064
#define IDC_BTN_DOORMODE2               1064
#define ID_LOGIN                        1065
#define IDC_BTN_GET_NXDOORMODE          1066
#define IDC_BTN_SET_NXDOORMODE          1067
#define IDC_UNAME                       1068
#define IDC_PWD                         1069
#define IDC_DOMAINNAME                  1070
#define IDC_BTN_ENERGIZE                1072
#define IDC_STATIC_PANEL_INIT           1073
#define IDC_BTN_INIT_START              1074
#define IDC_CHK_INPUTS__WINPAK          1075
#define IDC_CHK_GROUPS__WINPAK          1076
#define IDC_CHK_OUTPUTS__WINPAK         1077
#define IDC_CHK_CMD_FILES__WINPAK       1078
#define IDC_BTN_ADD_NOTE                1081
#define IDC_BTN_EXECUTE                 1082
#define IDC_STATIC_OPERATOR             1083
#define IDC_BTN_ACR_MODE                1085
#define IDC_BTN_DOOR_STATUS             1086
#define IDC_CMBDOMAINS                  1087
#define IDC_CMBDOMAIN                   1087
#define IDC_BTN_ACR_MODE2               1087
#define IDC_HBAC_GRP                    1088
#define IDD_CTP_ENTRANCE_TIMEZONE       8083
#define IDC_CTP_READER_MODE             8084
#define IDC_CTP_READER_DISABLE          8085
#define IDC_CTP_PANEL_COMBO_AD_READER_DISABLE_DOOR 8086
#define IDC_CTP__READER_LOCK            8087
#define IDC_CTP_PANEL_COMBO_AD_READER_LOCK 8088
#define IDC_CTP_READER_CARD_AND_PIN     8089
#define IDC_CTP_PANEL_COMBO_AD_READER_CARD_AND_PIN 8090
#define IDC_CTP_READER_STANDARD         8091
#define IDC_CTP_READER_SUPERVISOR       8092
#define IDC_CTP_READER_ESCORT           8093
#define IDC_CTP_READER_STAN_CARD_AND_PIN 8094
#define IDC_CTP_READER_SUPERVISOR_CARD_AND_PIN 8095
#define IDC_CTP_READER_ESCORT_CARD_AND_PIN 8096
#define IDC_CTP_READER_CARD_OR_PIN      8097
#define IDC_CTP_PANEL_COMBO_AD_READER_CARD_OR_PIN 8098
#define IDC_CTP_READER_STAN_CARD_OR_PIN 8099
#define IDC_CTP_READER_SUPERVISOR_CARD_OR_PIN 8100
#define IDC_CTP_READER_ESCORT_CARD_OR_PIN 8101
#define IDC_CTP_READER_PIN_ONLY         8102
#define IDC_CTP_PANEL_COMBO_AD_READER_PIN_ONLY 8103
#define IDC_CTP_READER_STAN_PIN_ONLY    8104
#define IDC_CTP_READER_SUPERVISOR_PIN_ONLY 8105
#define IDC_CTP_READER_ESCORT_PIN_ONLY  8106
#define IDC_CTP_READER_CARD_ONLY        8107
#define IDC_CTP_PANEL_COMBO_AD_READER_CARD_ONLY 8108
#define IDC_CTP_READER_STAN_CARD_ONLY   8109
#define IDC_CTP_READER_SUPERVISOR_CARD_ONLY 8110
#define IDC_CTP_READER_ESCORT_CARD_ONLY 8111
#define IDC_CTP_ED_READER_READONLY_NOTE 8112
#define IDC_CHK_BASIC_CONFIG__WINPAK    8201
#define IDC_CHK_SCP_TIME__WINPAK        8202
#define IDC_CHK_ACCESS_LEVEL__WINPAK    8203
#define IDC_CHK_SIO__WINPAK             8204
#define IDC_CHK_HOLIDAY__WINPAK         8205
#define IDC_CHK_TIMEZONE__WINPAK        8206
#define IDC_CHK_TRIGGER__WINPAK         8207
#define IDC_CHK_MP_GROUP__WINPAK        8208
#define IDC_CHK_CARD_FMT__WINPAK        8209
#define IDC_BTN_SELECTALL__WINPAK       8210
#define IDC_CHK_INP_SCAN_CNV__WINPAK    8211
#define IDC_CHK_ACCESS_AREA__WINPAK     8212
#define IDC_CHK_READER_LED__WINPAK      8213
#define IDC_CHK_CARD__WINPAK            8214
#define IDC_CHK_PROC_ACTION__WINPAK     8215
#define IDC_CHK_TZREFRESH__WINPAK       8217
#define IDC_CHK_SCP_CONFIG__WINPAK      8218
#define IDC_CHK_ENCRYPT__WINPAK         8219
#define ID_FILE_EXIT                    32771
#define ID_FILE_LOGIN                   32772
#define ID_FILE_LOGOUT                  32773
#define ID_OPERATIONS_PANELINITIALIZE   32774
#define ID_OPERATIONS_PANELCONTROL      32774
#define ID_OPERATIONS_OTHERADVCONTROLS  32776
#define ID_HELP_ABOUT                   32777

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        141
#define _APS_NEXT_COMMAND_VALUE         32778
#define _APS_NEXT_CONTROL_VALUE         1089
#define _APS_NEXT_SYMED_VALUE           106
#endif
#endif
